
language: node_js

node_js:
  - node
  - 10
  - 8
  - 6

sudo: false

after_success: npm run coverage

notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never